### ISSUE TITLE
OpenVINO image is not notified in the Dashboard while it is building

### ISSUE THREAD

**Issue by jeff-phillips-18** [red-hat-data-services/odh-dashboard#148]
**Describe the bug**
OpenVino builds do not show notifications for current status.

**Steps To Reproduce**

1.  Go to OpenShift Dedicated > Operators > Installed Operators > OpenVINO toolkit (ns: redhat-ods-applications) > Notebook
2. Click on "Create notebook"
3. Fill the mandatory fields
4. click on "Create" button
5. Go to Builds section 
6. Check if the open vino images is building
7. Go to RHODS Dashboard
8. Check that no notification message are displayed

**Expected behavior**
Notification messages saying "notebook images are building" appearing in RHODS Dashboard

**Workaround (if any)**
Add the label `opendatahub.io/build_type=notebook_image` to the OpenVino build config

**Comment by jeff-phillips-18** [comment]
@kkasravi This is something the OpenVino operator would need to be modified to do (adding the label `opendatahub.io/build_type=notebook_image` to the build config), not sure if you are the right contact but thought I'd give it a shot.

**Comment by Xaenalt** [comment]
See https://github.com/openvinotoolkit/model_server/pull/936

**Comment by dtrawins** [comment]
It is fixed in latest release 1.1.0 https://github.com/openvinotoolkit/operator/releases/tag/v1.1.0
