### ISSUE TITLE
[Feature Request]: update manifests to match whats in the downstream odh-manifests odh-dashboard

### ISSUE THREAD

**Issue by zdtsw** [red-hat-data-services/odh-dashboard#296]
### Feature description

We are moving towards the solution to deprecate odh-manifests repo.
Mainly for dashboard it is https://github.com/red-hat-data-services/odh-manifests/tree/master/odh-dashboard
the new location to use for RHODS build will be https://github.com/red-hat-data-services/odh-dashboard/tree/main/manifests

This issue is to check if any updates are needed in odh-dashboard and if it is either the folder here or the operator will be updated accordingly
e.g https://github.com/red-hat-data-services/odh-manifests/tree/master/odh-dashboard/overlays/rhods does not exist in this repo,  should the path still be `overlay/rhods` for operator to use or something else
e.g https://github.com/red-hat-data-services/odh-manifests/tree/master/partners/anaconda/base do dashboard want to host it, or move to operator

**Comment by andrewballantyne** [comment]
We did not get to talking about it at the Architectural Council ([slack message](https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1696362937841969?thread_ts=1695892681.459929&cid=C05NXTEHLGY)). But the topic is floated to support a "Product Release" repo of JUST RHODS resources. Keeping the component of ODH Dashboard pure of having to include RHODS items upstream.

Today we sync ODH `main` 1-1 with RHODS... there is no room to have additional commits & RHODS specific manifests.

**Comment by zdtsw** [comment]
we can close this issue, 
the work for dashboard has been done for the transition from ODH odh-manifests to ODH odh-dashboard
