### ISSUE TITLE
UX updates to microcopy in Dashboard

### ISSUE THREAD

**Issue by kywalker-rh** [red-hat-data-services/odh-dashboard#46]
Masthead:
- Remove Alert (BellIcon) and Settings (CogIcon) icons
- Replace with (QuestionCircleIcon) icon 

(QuestionCircleIcon) menu:
- "Documentation (ExternalLinkAltIcon)" link: https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html-single/getting_started_with_red_hat_openshift_data_science/
- "Support (ExternalLinkAltIcon)" link: https://access.redhat.com/support/cases/#/case/new/open-case?caseCreate=true

Enabled Cards:
- Kebab drop down: Add (ExternalLinkAltIcon) after Documentation and Launch menu items
- Change "Start tour" button to "Quick start"
- Change "Endpoint" to "Access endpoint"

Explore page:
- Change description text to say "Add optional applications to your Red Hat OpenShift Data Science instance."
- Card label: change "Self managed" to "Self-managed" (add hyphen)

Resources page:
- Change description text to say "Access all learning resources for Red Hat OpenShift Data Science and supported applications."
Card actions:
- Documentation card action: "View documentation (ExternalLinkAltIcon)"
- Quick start actions: "Start" before its been started; "Continue" on left "Restart" on right if quick start has been started
- How-to action: "Read How-to article (ExternalLinkAltIcon)"
- Tutorial action: "Access tutorial (ExternalLinkAltIcon)"

**Comment by jeff-phillips-18** [comment]
> * Change "Start tour" button to "Quick start"

The text updates based on the status of the quick start. Currently we use:
- Start tour
- Resume tour
- Restart tour
- Close tour

@kywalker-rh Do we want to change just the `Start tour` or others as well?

Could you also list which side of the card each status should appear on in the Resources page?

**Comment by jeff-phillips-18** [comment]
Is the Documentation link still WIP?

**Comment by kywalker-rh** [comment]
> The text updates based on the status of the quick start. Currently we use:
> 
> Start tour
> Resume tour
> Restart tour
> Close tour

@jeff-phillips-18 We want to change all of them, I changed them. I mapped them below to make it more clear:

Start tour -> Start
Resume tour -> Continue (Once started it replaces "Start" on the left side)
Restart tour -> Restart (Once started, it is shown on the right of the card, at the same time as "Continue")
Close tour -> Close (keep on left side, as currently implemented)

**Comment by kywalker-rh** [comment]
> Is the Documentation link still WIP?

Yes, it will be live at Summit, but at the moment it doesn't work.
