### ISSUE TITLE
RHOSAK documentation link in Explore displays incorrectly

### ISSUE THREAD

**Issue by kywalker-rh** [red-hat-data-services/odh-dashboard#53]
The documentation link in the Explore page displays the incorrect link. The link does take the user to the correct site after clicking it, however.

1. Go to 'Explore page'
2. Click on 'OpenShift Stream for Apache Kafka' card
3. Scroll down to 'For more information visit'
4. The link displays as: https://access.redhat.com/documentation/en-us/redhatopenshiftstreamsforapachekafka with italics for hat, streams, and apache

The link should display as https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka

This is seen in the pilot version: https://odh-dashboard-redhat-ods-applications.apps.rhods-internal.ju9j.p1.openshiftapps.com/explore?selectId=rhosak

I expect something happened with the formatting, since _<xx>_ puts italics around a word.

**Comment by jeff-phillips-18** [comment]
Fixed by https://github.com/red-hat-data-services/odh-dashboard/pull/55
