### ISSUE TITLE
Quick start actions don't follow the standard

### ISSUE THREAD

**Issue by kywalker-rh** [red-hat-data-services/odh-dashboard#78]
The Start, Restart, and Continue buttons on the bottom of the quick start cards are located in different places than the buttons on typical quick starts in other programs.

The existing buttons:
<img width="1183" alt="Screen Shot 2021-05-13 at 2 21 25 PM" src="https://user-images.githubusercontent.com/53235442/118284458-71ae1a80-b49e-11eb-9341-f665fc0f8db1.png">

The expected placement for the buttons:
![Screen Shot 2021-05-14 at 10 15 18 AM](https://user-images.githubusercontent.com/53235442/118284491-7bd01900-b49e-11eb-915f-12415bbe03f2.png)

**Comment by jeff-phillips-18** [comment]
This issue has been resolved
